version: '3.8'
services:
  fastapi:
    build: .
    container_name: fastapi_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
